<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-IQ9LTDG5" failures="1" tests="3" name="testcases.E2ETest" time="55.967" errors="0" timestamp="2023-07-15T18:14:21 IST" skipped="1">
  <testcase classname="testcases.E2ETest" name="e2e_searchFlight_toAndFromCity1" time="19.238">
    <failure message=" . Mismatch Found for expected [Welcome to India] but found [Welcome]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError:  . Mismatch Found for expected [Welcome to India] but found [Welcome]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at testcases.E2ETest.e2e_searchFlight_toAndFromCity1(E2ETest.java:73)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.retryFailed(TestInvoker.java:214)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:58)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:425)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:66)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- e2e_searchFlight_toAndFromCity1 -->
  <system-out>
e2e_searchFlight_toAndFromCity1Test cases is Failed  </system-out>
  <testcase classname="testcases.E2ETest" name="e2e_select_toAndFromCity" time="16.917"/>
  <system-out>
e2e_select_toAndFromCityTest cases is Passed  </system-out>
  <testcase classname="testcases.E2ETest" name="e2e_searchFlight_toAndFromCity1" time="19.812">
    <skipped/>
  </testcase> <!-- e2e_searchFlight_toAndFromCity1 -->
  <system-out>
Retrying e2e_searchFlight_toAndFromCity1 test cases with status FAILURE for the 1 time e2e_searchFlight_toAndFromCity1Test cases skipped by Listeners due to :- java.lang.AssertionError:  . Mismatch Found for expected [Welcome to India] but found [Welcome]  </system-out>
</testsuite> <!-- testcases.E2ETest -->
